### ISSUE TITLE
Disabled mic icon should probably be more obvious

### ISSUE THREAD

**Issue by ajgregory** [bnsoftware/SOM-ChromeExtension#18]
@holajura the icon for disabled audio probably needs to be more obvious so users can easily see its disabled since I'm thinking we store that as a preference and reuse.  Maybe a red slash or make the background red?

Here's current:
![image](https://user-images.githubusercontent.com/198646/125363028-bdf1cb80-e324-11eb-8182-caa4a5c09dfb.png)

**Comment by holajura** [comment]
Agree–Red is good. I don't think we should show the bouncing green mic in this case... It should be flat.
[mic-off.zip](https://github.com/bnsoftware/SOM-ChromeExtension/files/6808716/mic-off.zip)
